#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""字符串工具页面"""
from PyQt5.QtWidgets import QApplication
from siui.components.option_card import SiOptionCardPlane
from siui.components.page import SiPage
from siui.components.titled_widget_group import SiTitledWidgetGroup
from siui.components.widgets import SiDenseHContainer, SiLabel, SiLineEdit, SiPushButton, SiSwitch
from siui.core import Si, SiGlobal
from src.core.string_utils import StringUtils
from src.ui.components.copyable_text import CopyableTextArea

class StringToolsPage(SiPage):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.scroll_container = SiTitledWidgetGroup(self)
        self.body_area = SiLabel(self)
        self.body_area.setSiliconWidgetFlag(Si.EnableAnimationSignals)
        self.body_area.resized.connect(lambda _: self.scroll_container.adjustSize())
        self.titled_widget_group = SiTitledWidgetGroup(self.body_area)
        self.titled_widget_group.setSiliconWidgetFlag(Si.EnableAnimationSignals)
        self.titled_widget_group.resized.connect(lambda size: self.body_area.setFixedHeight(size[1]))
        self.titled_widget_group.move(64, 32)
        self.titled_widget_group.setSpacing(16)
        self.titled_widget_group.addTitle("随机字符串生成")
        self.titled_widget_group.addWidget(self._create_random_string_panel())
        self.titled_widget_group.addTitle("GUID / UUID 生成")
        self.titled_widget_group.addWidget(self._create_guid_panel())
        self.titled_widget_group.addTitle("Base64 编解码")
        self.titled_widget_group.addWidget(self._create_base64_panel())
        self.titled_widget_group.addTitle("URL 编解码")
        self.titled_widget_group.addWidget(self._create_url_panel())
        self.titled_widget_group.addTitle("JSON 格式化")
        self.titled_widget_group.addWidget(self._create_json_panel())
        self.titled_widget_group.addTitle("正则表达式测试")
        self.titled_widget_group.addWidget(self._create_regex_panel())
        self.titled_widget_group.addTitle("字符串哈希计算")
        self.titled_widget_group.addWidget(self._create_hash_panel())
        self.titled_widget_group.addPlaceholder(64)
        self.body_area.setFixedHeight(self.titled_widget_group.height())
        self.scroll_container.addWidget(self.body_area)
        self.setAttachment(self.scroll_container)

    def _create_random_string_panel(self):
        panel = SiOptionCardPlane(self)
        panel.setTitle("生成随机字符串")
        length_row = SiDenseHContainer(self)
        length_row.setFixedHeight(40)
        length_row.setSpacing(12)
        length_label = SiLabel(self)
        length_label.setText("长度:")
        length_label.setFixedWidth(50)
        text_color = SiGlobal.siui.colors['TEXT_A']
        length_label.setStyleSheet(f"color: {text_color};")
        self.random_length_edit = SiLineEdit(self)
        self.random_length_edit.setFixedSize(120, 36)
        self.random_length_edit.lineEdit().setText("16")
        count_label = SiLabel(self)
        count_label.setText("数量:")
        count_label.setFixedWidth(50)
        text_color = SiGlobal.siui.colors['TEXT_A']
        count_label.setStyleSheet(f"color: {text_color};")
        self.random_count_edit = SiLineEdit(self)
        self.random_count_edit.setFixedSize(120, 36)
        self.random_count_edit.lineEdit().setText("1")
        length_row.addWidget(length_label)
        length_row.addWidget(self.random_length_edit)
        length_row.addWidget(count_label)
        length_row.addWidget(self.random_count_edit)
        options_row = SiDenseHContainer(self)
        options_row.setFixedHeight(40)
        options_row.setSpacing(16)
        self.use_uppercase = SiSwitch(self)
        self.use_uppercase.setFixedHeight(32)
        self.use_uppercase.setChecked(True)
        text_color = SiGlobal.siui.colors['TEXT_A']
        uppercase_label = SiLabel(self)
        uppercase_label.setText("大写字母")
        uppercase_label.setStyleSheet(f"color: {text_color};")
        self.use_lowercase = SiSwitch(self)
        self.use_lowercase.setFixedHeight(32)
        self.use_lowercase.setChecked(True)
        lowercase_label = SiLabel(self)
        lowercase_label.setText("小写字母")
        lowercase_label.setStyleSheet(f"color: {text_color};")
        self.use_digits = SiSwitch(self)
        self.use_digits.setFixedHeight(32)
        self.use_digits.setChecked(True)
        digits_label = SiLabel(self)
        digits_label.setText("数字")
        digits_label.setStyleSheet(f"color: {text_color};")
        self.use_special = SiSwitch(self)
        self.use_special.setFixedHeight(32)
        special_label = SiLabel(self)
        special_label.setText("特殊符号")
        special_label.setStyleSheet(f"color: {text_color};")
        options_row.addWidget(uppercase_label)
        options_row.addWidget(self.use_uppercase)
        options_row.addWidget(lowercase_label)
        options_row.addWidget(self.use_lowercase)
        options_row.addWidget(digits_label)
        options_row.addWidget(self.use_digits)
        options_row.addWidget(special_label)
        options_row.addWidget(self.use_special)
        action_row = SiDenseHContainer(self)
        action_row.setFixedHeight(40)
        generate_btn = SiPushButton(self)
        generate_btn.resize(120, 36)
        generate_btn.setUseTransition(True)
        generate_btn.attachment().setText("生成")
        generate_btn.clicked.connect(self._generate_random_string)
        action_row.addWidget(generate_btn)
        self.random_result = CopyableTextArea(self, monospace=True, min_height=60, max_height=150)
        self.random_result.setText("点击生成按钮生成随机字符串")
        panel.body().addWidget(length_row)
        panel.body().addWidget(options_row)
        panel.body().addWidget(action_row)
        panel.body().addWidget(self.random_result)
        panel.adjustSize()
        return panel

    def _create_guid_panel(self):
        panel = SiOptionCardPlane(self)
        panel.setTitle("生成GUID/UUID (Unity常用)")
        action_row = SiDenseHContainer(self)
        action_row.setFixedHeight(40)
        action_row.setSpacing(12)
        guid_btn = SiPushButton(self)
        guid_btn.resize(140, 36)
        guid_btn.setUseTransition(True)
        guid_btn.attachment().setText("生成GUID")
        guid_btn.clicked.connect(self._generate_guid)
        uuid_btn = SiPushButton(self)
        uuid_btn.resize(140, 36)
        uuid_btn.attachment().setText("生成UUID")
        uuid_btn.clicked.connect(self._generate_uuid)
        action_row.addWidget(guid_btn)
        action_row.addWidget(uuid_btn)
        self.guid_result = CopyableTextArea(self, monospace=True, min_height=40, max_height=80)
        self.guid_result.setText("点击按钮生成")
        panel.body().addWidget(action_row)
        panel.body().addWidget(self.guid_result)
        panel.adjustSize()
        return panel

    def _create_base64_panel(self):
        panel = SiOptionCardPlane(self)
        panel.setTitle("Base64 编码/解码")
        self.base64_input = SiLineEdit(self)
        self.base64_input.setFixedHeight(36)
        self.base64_input.lineEdit().setPlaceholderText("输入文本...")
        action_row = SiDenseHContainer(self)
        action_row.setFixedHeight(40)
        action_row.setSpacing(12)
        encode_btn = SiPushButton(self)
        encode_btn.resize(100, 36)
        encode_btn.attachment().setText("编码")
        encode_btn.clicked.connect(self._base64_encode)
        decode_btn = SiPushButton(self)
        decode_btn.resize(100, 36)
        decode_btn.attachment().setText("解码")
        decode_btn.clicked.connect(self._base64_decode)
        action_row.addWidget(encode_btn)
        action_row.addWidget(decode_btn)
        self.base64_result = CopyableTextArea(self, monospace=True, min_height=60, max_height=150)
        self.base64_result.setText("-")
        panel.body().setAdjustWidgetsSize(True)
        panel.body().addWidget(self.base64_input)
        panel.body().addWidget(action_row)
        panel.body().addWidget(self.base64_result)
        panel.adjustSize()
        return panel

    def _create_url_panel(self):
        panel = SiOptionCardPlane(self)
        panel.setTitle("URL 编码/解码")
        self.url_input = SiLineEdit(self)
        self.url_input.setFixedHeight(36)
        self.url_input.lineEdit().setPlaceholderText("输入URL或文本...")
        action_row = SiDenseHContainer(self)
        action_row.setFixedHeight(40)
        action_row.setSpacing(12)
        encode_btn = SiPushButton(self)
        encode_btn.resize(100, 36)
        encode_btn.attachment().setText("编码")
        encode_btn.clicked.connect(self._url_encode)
        decode_btn = SiPushButton(self)
        decode_btn.resize(100, 36)
        decode_btn.attachment().setText("解码")
        decode_btn.clicked.connect(self._url_decode)
        action_row.addWidget(encode_btn)
        action_row.addWidget(decode_btn)
        self.url_result = CopyableTextArea(self, monospace=False, min_height=60, max_height=150)
        self.url_result.setText("-")
        panel.body().setAdjustWidgetsSize(True)
        panel.body().addWidget(self.url_input)
        panel.body().addWidget(action_row)
        panel.body().addWidget(self.url_result)
        panel.adjustSize()
        return panel

    def _create_json_panel(self):
        panel = SiOptionCardPlane(self)
        panel.setTitle("JSON 格式化/压缩")
        self.json_input = SiLineEdit(self)
        self.json_input.setFixedHeight(36)
        self.json_input.lineEdit().setPlaceholderText("输入JSON字符串...")
        action_row = SiDenseHContainer(self)
        action_row.setFixedHeight(40)
        action_row.setSpacing(12)
        format_btn = SiPushButton(self)
        format_btn.resize(100, 36)
        format_btn.attachment().setText("格式化")
        format_btn.clicked.connect(self._json_format)
        minify_btn = SiPushButton(self)
        minify_btn.resize(100, 36)
        minify_btn.attachment().setText("压缩")
        minify_btn.clicked.connect(self._json_minify)
        validate_btn = SiPushButton(self)
        validate_btn.resize(100, 36)
        validate_btn.attachment().setText("验证")
        validate_btn.clicked.connect(self._json_validate)
        action_row.addWidget(format_btn)
        action_row.addWidget(minify_btn)
        action_row.addWidget(validate_btn)
        self.json_result = CopyableTextArea(self, monospace=True, min_height=80, max_height=200)
        self.json_result.setText("-")
        panel.body().setAdjustWidgetsSize(True)
        panel.body().addWidget(self.json_input)
        panel.body().addWidget(action_row)
        panel.body().addWidget(self.json_result)
        panel.adjustSize()
        return panel

    def _create_regex_panel(self):
        panel = SiOptionCardPlane(self)
        panel.setTitle("正则表达式测试")
        self.regex_pattern = SiLineEdit(self)
        self.regex_pattern.setFixedHeight(36)
        self.regex_pattern.lineEdit().setPlaceholderText("输入正则表达式...")
        self.regex_text = SiLineEdit(self)
        self.regex_text.setFixedHeight(36)
        self.regex_text.lineEdit().setPlaceholderText("输入测试文本...")
        action_row = SiDenseHContainer(self)
        action_row.setFixedHeight(40)
        test_btn = SiPushButton(self)
        test_btn.resize(100, 36)
        test_btn.setUseTransition(True)
        test_btn.attachment().setText("测试")
        test_btn.clicked.connect(self._regex_test)
        action_row.addWidget(test_btn)
        self.regex_result = CopyableTextArea(self, monospace=False, min_height=60, max_height=150)
        self.regex_result.setText("-")
        panel.body().setAdjustWidgetsSize(True)
        panel.body().addWidget(self.regex_pattern)
        panel.body().addWidget(self.regex_text)
        panel.body().addWidget(action_row)
        panel.body().addWidget(self.regex_result)
        panel.adjustSize()
        return panel

    def _create_hash_panel(self):
        panel = SiOptionCardPlane(self)
        panel.setTitle("字符串哈希计算")
        self.hash_input = SiLineEdit(self)
        self.hash_input.setFixedHeight(36)
        self.hash_input.lineEdit().setPlaceholderText("输入要计算哈希的文本...")
        action_row = SiDenseHContainer(self)
        action_row.setFixedHeight(40)
        calc_btn = SiPushButton(self)
        calc_btn.resize(120, 36)
        calc_btn.setUseTransition(True)
        calc_btn.attachment().setText("计算哈希")
        calc_btn.clicked.connect(self._calc_hash)
        action_row.addWidget(calc_btn)
        self.hash_result = CopyableTextArea(self, monospace=True, min_height=80, max_height=150)
        self.hash_result.setText("-")
        panel.body().setAdjustWidgetsSize(True)
        panel.body().addWidget(self.hash_input)
        panel.body().addWidget(action_row)
        panel.body().addWidget(self.hash_result)
        panel.adjustSize()
        return panel

    def _generate_random_string(self):
        try:
            length = int(self.random_length_edit.lineEdit().text() or "16")
            count = int(self.random_count_edit.lineEdit().text() or "1")
            results = StringUtils.generate_multiple_strings(count=count, length=length, use_uppercase=self.use_uppercase.isChecked(), use_lowercase=self.use_lowercase.isChecked(), use_digits=self.use_digits.isChecked(), use_special=self.use_special.isChecked())
            self.random_result.setText("\n".join(results))
        except Exception as e: self.random_result.setText(f"错误: {e}")

    def _generate_guid(self): self.guid_result.setText(StringUtils.generate_guid())
    def _generate_uuid(self): self.guid_result.setText(StringUtils.generate_uuid())
    def _base64_encode(self):
        try: self.base64_result.setText(StringUtils.base64_encode(self.base64_input.lineEdit().text()))
        except Exception as e: self.base64_result.setText(f"错误: {e}")
    def _base64_decode(self):
        try: self.base64_result.setText(StringUtils.base64_decode(self.base64_input.lineEdit().text()))
        except Exception as e: self.base64_result.setText(f"错误: {e}")
    def _url_encode(self): self.url_result.setText(StringUtils.url_encode(self.url_input.lineEdit().text()))
    def _url_decode(self): self.url_result.setText(StringUtils.url_decode(self.url_input.lineEdit().text()))
    def _json_format(self):
        try: self.json_result.setText(StringUtils.json_format(self.json_input.lineEdit().text()))
        except Exception as e: self.json_result.setText(f"JSON格式错误: {e}")
    def _json_minify(self):
        try: self.json_result.setText(StringUtils.json_minify(self.json_input.lineEdit().text()))
        except Exception as e: self.json_result.setText(f"JSON格式错误: {e}")
    def _json_validate(self):
        valid, msg = StringUtils.json_validate(self.json_input.lineEdit().text())
        self.json_result.setText(msg)
    def _regex_test(self):
        result = StringUtils.regex_test(self.regex_pattern.lineEdit().text(), self.regex_text.lineEdit().text())
        if not result["is_valid"]: self.regex_result.setText(f"正则表达式错误: {result['error']}")
        elif result["matches"]:
            text = f"找到 {len(result['matches'])} 个匹配:\n"
            for m in result["matches"][:10]: text += f"  * \"{m['match']}\" (位置: {m['start']}-{m['end']})\n"
            self.regex_result.setText(text)
        else: self.regex_result.setText("没有找到匹配")
    def _calc_hash(self):
        text = self.hash_input.lineEdit().text()
        self.hash_result.setText(f"MD5:    {StringUtils.hash_md5(text)}\nSHA1:   {StringUtils.hash_sha1(text)}\nSHA256: {StringUtils.hash_sha256(text)}")

    def resizeEvent(self, event):
        super().resizeEvent(event)
        w = event.size().width()
        if w > 200:
            self.body_area.setFixedWidth(w)
            self.titled_widget_group.setFixedWidth(min(w - 128, 1200))
